### PR TITLE
Update Go version to 1.23.4

### PR DESCRIPTION
**Pull request by uclalibraryservicesrobot**
This PR updates the Go version in the go.mod file to the latest available version.

### CODE REVIEW

**Review by DRickard — APPROVED** [review]

**Review by ksclarke — APPROVED** [review]

**Comment by ksclarke** [comment]
We need to update to macos-13

**Comment by DRickard** [comment]
> We need to update to macos-13

Dmed with Angela 

> We need to update to macos-13

Dmed with Angela on this WRT the 1137 branch... she's of the opinion that as long as the macos-latest build succeeds, we don't specific version (e.g., macos-13 or later) builds/tests.

**Comment by ksclarke** [comment]
Okay, sounds good. I think at first we needed a particular version to get the intel release, but we've since switched to goreleaser which I guess handles all that for us magically.

**Comment by ksclarke** [comment]
Hey, @DRickard, I chatted with @angelahuqing today, and we concluded we'll want to add a latest for ARM and a latest for Intel. See the links in Slack for how to reference each of those in the build.yml's matrix.

**Review by DRickard — APPROVED** [review]

**Pull request merged**
